Repository devarshishimpi/stonecss, pull requests merged in 2022-07, with the labels that each got.

#4 CSS update and more
  assets/cloud.svg
  assets/fast.svg
  assets/favicon.ico
  assets/feedback.svg
  assets/integrated.svg
  assets/logo.svg
  index.html
  style.css
Labels: enhancement

#5 Update contribution guidelines and more
  CONTRIBUTING.md
  index.html
  index.js
Labels: enhancement

#7 New PR of the same topic
  404.html
  assets/404.svg
  index.html
  style.css
Labels: duplicate, enhancement

#9 8 second to features and changes with that
  index.html
  style.css
Labels: bug, enhancement

#14 11 logo does not take to homepage
  404.html
  index.html
Labels: bug
